# Change these first
owner: mstdn-social # Your GitHub organization or username, where this repository lives
repo: status.mstdn-social.com # The name of this repository

sites:
  - name: mstdn-social.com
    url: https://mstdn-social.com
  - name: files.mstdn-social.com
    url: https://files.mstdn-social.com/index.html

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mstdn-social.com
  # baseUrl: /your-repo-name
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: mstdn-social
  introTitle: "**mstdn-social** is a Mastodon server."
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://mstdn-social.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
